# Generated by Django 4.2 on 2023-05-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
            ],
        ),
    ]
